version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  config_server:
    build: ./ConfigServer
    image: config_server:0.0.1
    container_name: config-server
    ports:
      - "8888:8888"

  query_side_service:
    build:
      context: ./CQRS_query_model
    image: query_side_service:0.0.1
    container_name: query-side-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    depends_on:
      - rabbitmq
      - config_server


  command_side_service:
    build:
      context: ./CQRS_command_model
    image: command_side_service:0.0.1
    container_name: command_side_service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    depends_on:
      - rabbitmq
      - config_server





