version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      -5672:5672
      -15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  query_side_service:
    image: command_side_service:0.0.1
    container_name: query_side_service
    ports:
    - 8082:8082
    depends_on:
      - rabbitmq


  command_side_service:
    image: query_side_service:0.0.1
    container_name: command_side_service
    ports:
    - 8081:8081
    depends_on:
      - rabbitmq