server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
axon:
  amqp:
    exchange: axon-exchange